Git Script Manager
==================
:author: Peter Cummuskey
:email: peterc@aetheric.co.nz

This utility will allow you to manage your git scripts in a less-than-horrible
fashion. 

== Commands

There are a few commands for dealing with the repos and symlinks.

=== get

Fetches, updates, and/or checks-out a branch of a provided github repository.

e.g. git scripts get tzrlk/git-extras master

NOTE: If the last argument is omitted, it will default to 'master'

TODO: Remove reliance on github.

=== on

Selects a particular script and symlinks it into the ~/.git/script-bin
directory for use.

e.g. git scripts on tzrlk/git-extras bin/git-ignore git-ignore

TODO: Make the last argument optional

TODO: Automatically 'get' repo if not alread fetched (only with option)

TODO: Add recursive searching for scripts so the subdir doesn't need to be
specified.

=== off

Removes a particular script from use.

e.g. git scripts off git-ignore

=== purge

Removes a script repo and all associated activated scripts.

e.g. git scripts purge tzrlk/git-extras

TODO: Make this more than an rm -rf on the repo dir. Should clean-up symlinks.

=== list

Lists all the script repos, their scripts, and whether they are activated or
not.

e.g. git scripts list

TODO: Actually add recursive script search and matching. Ugh.

== Installation

Scripts are provided for installation, but for any environment, the first step
is to clone this repository to some directory on your computer.

=== Windows

Execute install.cmd and it will use powershell to create the correct PATH
entries for you.

NOTE: This doesn't actually work at the moment, so you'll need to start a
powershell session under administrator mode, and set the ExecutionPolicy to
Bypass; finally, run the script file. The install.cmd file just attempts to do
this all for you. 

=== Linux

I haven't written the install scripts for linux yet.

=== Manual

Just add the bin directory and ~/.git/script-bin to your PATH. That's it.

